name: Rush Bot Test Workflow

schedules:
  - cron: '0 14 * * *'
    displayName: message schedule
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: run_avatarbot
    steps:
      - checkout: self
      
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'

      - script: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: "Installing Requirements"

      - task: PythonScript@0
        inputs:
          scriptSource: 'filePath'
          scriptPath: 'RushBot.py'
        env:
          BOT_ID: $(BOT_ID)
        displayName: 'Run Script'