name: GroupMe Bot Test Workflow

on:
  push
  #schedule:
    #- cron: "42 21 * * *"

jobs:
  run-testbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'

      - name: Download Requirements
        run: python -m pip install -r requirements.txt
      
      - name: Run Python Script
        env:
          TEST_BOT_ID: ${{ secrets.TEST_BOT_ID }}
        run: python TestBot.py