name: GroupMe Bot Test Workflow

on:
  schedule:
    - cron: "42 21 * * *"

jobs:
  run-testbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'
      
      - name: Run Python Script
        run: |
          python -m pip install -r requirements.txt
          python TestBot.py